// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: CEMM.proto

package cemm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          []byte                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Node          []byte                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToken) Reset() {
	*x = AddToken{}
	mi := &file_CEMM_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToken) ProtoMessage() {}

func (x *AddToken) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToken.ProtoReflect.Descriptor instead.
func (*AddToken) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{0}
}

func (x *AddToken) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *AddToken) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

type InitTagSetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          [][]byte               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"` //关键字空间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitTagSetsRequest) Reset() {
	*x = InitTagSetsRequest{}
	mi := &file_CEMM_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitTagSetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitTagSetsRequest) ProtoMessage() {}

func (x *InitTagSetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitTagSetsRequest.ProtoReflect.Descriptor instead.
func (*InitTagSetsRequest) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{1}
}

func (x *InitTagSetsRequest) GetTags() [][]byte {
	if x != nil {
		return x.Tags
	}
	return nil
}

type InitEDBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *AddToken              `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` //EDB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitEDBRequest) Reset() {
	*x = InitEDBRequest{}
	mi := &file_CEMM_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitEDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitEDBRequest) ProtoMessage() {}

func (x *InitEDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitEDBRequest.ProtoReflect.Descriptor instead.
func (*InitEDBRequest) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{2}
}

func (x *InitEDBRequest) GetToken() *AddToken {
	if x != nil {
		return x.Token
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Tag           []byte                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Addr          []byte                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	DummyTokens   []*AddToken            `protobuf:"bytes,4,rep,name=dummyTokens,proto3" json:"dummyTokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_CEMM_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *GetRequest) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *GetRequest) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *GetRequest) GetDummyTokens() []*AddToken {
	if x != nil {
		return x.DummyTokens
	}
	return nil
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          []byte                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_CEMM_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{4}
}

func (x *GetReply) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Tag           []byte                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Tokens        []*AddToken            `protobuf:"bytes,3,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_CEMM_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{5}
}

func (x *AddRequest) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *AddRequest) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *AddRequest) GetTokens() []*AddToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            bool                   `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Tag           []byte                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundRequest) Reset() {
	*x = RoundRequest{}
	mi := &file_CEMM_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundRequest) ProtoMessage() {}

func (x *RoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundRequest.ProtoReflect.Descriptor instead.
func (*RoundRequest) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{6}
}

func (x *RoundRequest) GetOp() bool {
	if x != nil {
		return x.Op
	}
	return false
}

func (x *RoundRequest) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

type RoundReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundReply) Reset() {
	*x = RoundReply{}
	mi := &file_CEMM_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundReply) ProtoMessage() {}

func (x *RoundReply) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundReply.ProtoReflect.Descriptor instead.
func (*RoundReply) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{7}
}

func (x *RoundReply) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

var File_CEMM_proto protoreflect.FileDescriptor

var file_CEMM_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x43, 0x45,
	0x4d, 0x4d, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x32, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x22, 0x28, 0x0a, 0x12, 0x49, 0x6e, 0x69, 0x74, 0x54, 0x61, 0x67, 0x53, 0x65,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x36, 0x0a,
	0x0e, 0x49, 0x6e, 0x69, 0x74, 0x45, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x24, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x7a, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12,
	0x30, 0x0a, 0x0b, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x41, 0x64, 0x64, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x0b, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x73, 0x22, 0x1e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x22, 0x5c, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x26, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x41,
	0x64, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22,
	0x30, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x22, 0x22, 0x0a, 0x0a, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0x9f, 0x02, 0x0a, 0x04, 0x43, 0x45, 0x4d, 0x4d, 0x12, 0x2b,
	0x0a, 0x03, 0x67, 0x65, 0x74, 0x12, 0x10, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x30, 0x01, 0x12, 0x31, 0x0a, 0x03, 0x61,
	0x64, 0x64, 0x12, 0x10, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x37,
	0x0a, 0x0d, 0x67, 0x65, 0x74, 0x4f, 0x72, 0x49, 0x6e, 0x63, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12,
	0x12, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x54,
	0x61, 0x67, 0x53, 0x65, 0x74, 0x73, 0x12, 0x18, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x49, 0x6e,
	0x69, 0x74, 0x54, 0x61, 0x67, 0x53, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x07, 0x69, 0x6e,
	0x69, 0x74, 0x45, 0x44, 0x42, 0x12, 0x14, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x49, 0x6e, 0x69,
	0x74, 0x45, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x28, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x63, 0x65, 0x6d,
	0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_CEMM_proto_rawDescOnce sync.Once
	file_CEMM_proto_rawDescData []byte
)

func file_CEMM_proto_rawDescGZIP() []byte {
	file_CEMM_proto_rawDescOnce.Do(func() {
		file_CEMM_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CEMM_proto_rawDesc), len(file_CEMM_proto_rawDesc)))
	})
	return file_CEMM_proto_rawDescData
}

var file_CEMM_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_CEMM_proto_goTypes = []any{
	(*AddToken)(nil),           // 0: CEMM.AddToken
	(*InitTagSetsRequest)(nil), // 1: CEMM.InitTagSetsRequest
	(*InitEDBRequest)(nil),     // 2: CEMM.InitEDBRequest
	(*GetRequest)(nil),         // 3: CEMM.GetRequest
	(*GetReply)(nil),           // 4: CEMM.GetReply
	(*AddRequest)(nil),         // 5: CEMM.AddRequest
	(*RoundRequest)(nil),       // 6: CEMM.RoundRequest
	(*RoundReply)(nil),         // 7: CEMM.RoundReply
	(*emptypb.Empty)(nil),      // 8: google.protobuf.Empty
}
var file_CEMM_proto_depIdxs = []int32{
	0, // 0: CEMM.InitEDBRequest.token:type_name -> CEMM.AddToken
	0, // 1: CEMM.GetRequest.dummyTokens:type_name -> CEMM.AddToken
	0, // 2: CEMM.AddRequest.tokens:type_name -> CEMM.AddToken
	3, // 3: CEMM.CEMM.get:input_type -> CEMM.GetRequest
	5, // 4: CEMM.CEMM.add:input_type -> CEMM.AddRequest
	6, // 5: CEMM.CEMM.getOrIncRound:input_type -> CEMM.RoundRequest
	1, // 6: CEMM.CEMM.initTagSets:input_type -> CEMM.InitTagSetsRequest
	2, // 7: CEMM.CEMM.initEDB:input_type -> CEMM.InitEDBRequest
	4, // 8: CEMM.CEMM.get:output_type -> CEMM.GetReply
	8, // 9: CEMM.CEMM.add:output_type -> google.protobuf.Empty
	7, // 10: CEMM.CEMM.getOrIncRound:output_type -> CEMM.RoundReply
	8, // 11: CEMM.CEMM.initTagSets:output_type -> google.protobuf.Empty
	8, // 12: CEMM.CEMM.initEDB:output_type -> google.protobuf.Empty
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_CEMM_proto_init() }
func file_CEMM_proto_init() {
	if File_CEMM_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CEMM_proto_rawDesc), len(file_CEMM_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CEMM_proto_goTypes,
		DependencyIndexes: file_CEMM_proto_depIdxs,
		MessageInfos:      file_CEMM_proto_msgTypes,
	}.Build()
	File_CEMM_proto = out.File
	file_CEMM_proto_goTypes = nil
	file_CEMM_proto_depIdxs = nil
}
