// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: CEMM.proto

package cemm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          []byte                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Node          []byte                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToken) Reset() {
	*x = AddToken{}
	mi := &file_CEMM_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToken) ProtoMessage() {}

func (x *AddToken) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToken.ProtoReflect.Descriptor instead.
func (*AddToken) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{0}
}

func (x *AddToken) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

func (x *AddToken) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

// message InitTagSetsRequest
//
//	{
//	 repeated  bytes tags =1; //关键字空间
//	}
//
// message InitEDBRequest
//
//	{
//	 AddToken token =1; //EDB
//	}
type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          [][]byte               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"` //关键字空间
	Dummys        []*AddToken            `protobuf:"bytes,2,rep,name=dummys,proto3" json:"dummys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_CEMM_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetTags() [][]byte {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *InitRequest) GetDummys() []*AddToken {
	if x != nil {
		return x.Dummys
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           []byte                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Addr          []byte                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_CEMM_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *GetRequest) GetAddr() []byte {
	if x != nil {
		return x.Addr
	}
	return nil
}

type GetReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          []byte                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReply) Reset() {
	*x = GetReply{}
	mi := &file_CEMM_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReply) ProtoMessage() {}

func (x *GetReply) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReply.ProtoReflect.Descriptor instead.
func (*GetReply) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{3}
}

func (x *GetReply) GetNode() []byte {
	if x != nil {
		return x.Node
	}
	return nil
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*AddToken            `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_CEMM_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{4}
}

func (x *AddRequest) GetTokens() []*AddToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            bool                   `protobuf:"varint,1,opt,name=op,proto3" json:"op,omitempty"`
	Tag           []byte                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundRequest) Reset() {
	*x = RoundRequest{}
	mi := &file_CEMM_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundRequest) ProtoMessage() {}

func (x *RoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundRequest.ProtoReflect.Descriptor instead.
func (*RoundRequest) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{5}
}

func (x *RoundRequest) GetOp() bool {
	if x != nil {
		return x.Op
	}
	return false
}

func (x *RoundRequest) GetTag() []byte {
	if x != nil {
		return x.Tag
	}
	return nil
}

type RoundReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundReply) Reset() {
	*x = RoundReply{}
	mi := &file_CEMM_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundReply) ProtoMessage() {}

func (x *RoundReply) ProtoReflect() protoreflect.Message {
	mi := &file_CEMM_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundReply.ProtoReflect.Descriptor instead.
func (*RoundReply) Descriptor() ([]byte, []int) {
	return file_CEMM_proto_rawDescGZIP(), []int{6}
}

func (x *RoundReply) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

var File_CEMM_proto protoreflect.FileDescriptor

var file_CEMM_proto_rawDesc = string([]byte{
	0x0a, 0x0a, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x43, 0x45,
	0x4d, 0x4d, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x32, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e,
	0x6f, 0x64, 0x65, 0x22, 0x49, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x26, 0x0a, 0x06, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x41, 0x64,
	0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x06, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x73, 0x22, 0x32,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x12,
	0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x22, 0x1e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e, 0x6f,
	0x64, 0x65, 0x22, 0x34, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0x30, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x22, 0x0a, 0x0a, 0x52, 0x6f,
	0x75, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x32, 0xd4,
	0x01, 0x0a, 0x04, 0x43, 0x45, 0x4d, 0x4d, 0x12, 0x2b, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x12, 0x10,
	0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0e, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x30, 0x01, 0x12, 0x31, 0x0a, 0x03, 0x61, 0x64, 0x64, 0x12, 0x10, 0x2e, 0x43, 0x45,
	0x4d, 0x4d, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x4f, 0x72,
	0x49, 0x6e, 0x63, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x12, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e,
	0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x43,
	0x45, 0x4d, 0x4d, 0x2e, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x33, 0x0a, 0x04, 0x69, 0x6e, 0x69, 0x74, 0x12, 0x11, 0x2e, 0x43, 0x45, 0x4d, 0x4d, 0x2e,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x63, 0x65, 0x6d, 0x6d, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_CEMM_proto_rawDescOnce sync.Once
	file_CEMM_proto_rawDescData []byte
)

func file_CEMM_proto_rawDescGZIP() []byte {
	file_CEMM_proto_rawDescOnce.Do(func() {
		file_CEMM_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CEMM_proto_rawDesc), len(file_CEMM_proto_rawDesc)))
	})
	return file_CEMM_proto_rawDescData
}

var file_CEMM_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_CEMM_proto_goTypes = []any{
	(*AddToken)(nil),      // 0: CEMM.AddToken
	(*InitRequest)(nil),   // 1: CEMM.InitRequest
	(*GetRequest)(nil),    // 2: CEMM.GetRequest
	(*GetReply)(nil),      // 3: CEMM.GetReply
	(*AddRequest)(nil),    // 4: CEMM.AddRequest
	(*RoundRequest)(nil),  // 5: CEMM.RoundRequest
	(*RoundReply)(nil),    // 6: CEMM.RoundReply
	(*emptypb.Empty)(nil), // 7: google.protobuf.Empty
}
var file_CEMM_proto_depIdxs = []int32{
	0, // 0: CEMM.InitRequest.dummys:type_name -> CEMM.AddToken
	0, // 1: CEMM.AddRequest.tokens:type_name -> CEMM.AddToken
	2, // 2: CEMM.CEMM.get:input_type -> CEMM.GetRequest
	4, // 3: CEMM.CEMM.add:input_type -> CEMM.AddRequest
	5, // 4: CEMM.CEMM.getOrIncRound:input_type -> CEMM.RoundRequest
	1, // 5: CEMM.CEMM.init:input_type -> CEMM.InitRequest
	3, // 6: CEMM.CEMM.get:output_type -> CEMM.GetReply
	7, // 7: CEMM.CEMM.add:output_type -> google.protobuf.Empty
	6, // 8: CEMM.CEMM.getOrIncRound:output_type -> CEMM.RoundReply
	7, // 9: CEMM.CEMM.init:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_CEMM_proto_init() }
func file_CEMM_proto_init() {
	if File_CEMM_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CEMM_proto_rawDesc), len(file_CEMM_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CEMM_proto_goTypes,
		DependencyIndexes: file_CEMM_proto_depIdxs,
		MessageInfos:      file_CEMM_proto_msgTypes,
	}.Build()
	File_CEMM_proto = out.File
	file_CEMM_proto_goTypes = nil
	file_CEMM_proto_depIdxs = nil
}
